# Site Settings
title: "Lila Josey James" # Your site title
description: "Resume and Portfolio of Lila Josey James" # Optional site description
url: "https://yourusername.github.io" # Your site URL
baseurl: "/resume2025" # The repository name, include this if it's not your main GitHub Pages repo
author: "Lila Josey James" # Your name or site's author

# Theme Settings
remote_theme: pages-themes/minimal@v0.2.0 # The Minimal theme from GitHub Pages
plugins:
  - jekyll-remote-theme # Allows using remote themes

# Customization
markdown: kramdown # Default Markdown processor
highlighter: rouge # Code highlighting (optional)

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
