# Site Settings
title: "Lila Josey James" 
description: "Resume and Portfolio of Lila Josey James" 
url: "https://github.com/lilashiba" 
baseurl: "/resume2025" 
author: "Lila Josey James" 
# Theme Settings
remote_theme: pages-themes/minimal@v0.2.0 # The Minimal theme from GitHub Pages
plugins:
  - jekyll-remote-theme # Allows using remote themes

# Customization
markdown: kramdown # Default Markdown processor
highlighter: rouge # Code highlighting (optional)

# Include custom styles
sass:
  style: compressed

# Assets
include:
  - assets/css/style.scss

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
